### ISSUE TITLE
Traceback (most recent call last...

### ISSUE THREAD

**Issue by ghost** [yousefamar/irc-bot#2]
```
Traceback (most recent call last):
  File "parabot.py", line 103, in <module>
    main()
  File "parabot.py", line 99, in main
    bot = ParaBot("##channel", "nickname", "irc.freenode.net", 6667)
  File "parabot.py", line 43, in __init__
    self.brain = ParaBrain(self)
  File "parabot.py", line 29, in __init__

```

**Comment by ghost** [comment]
Any help is appreciated :)

**Comment by yousefamar** [comment]
Hi @ranyyy. Sorry I'm only replying now -- I've been pretty swamped. Did you get anywhere with this? I'll give it a look.

Honestly I'm surprised that anything still works since this repo has been abandoned for 5 years now.
